### ISSUE TITLE
Research Travis configuration

### ISSUE THREAD

**Issue by glebec** [FullstackAcademy/bones#71]
_From @glebec on February 24, 2017 4:49_

At Fullstack Academy, we've used Codeship successfully for many projects. However, as of this writing the free Codeship tier only permits configuration through the web UI (the pro account allows for in-repo yml configuration). One workaround is [Codeship-YAML](https://github.com/painless-software/codeship-yaml), though that requires a minimal 2-line Codeship config online plus one extra npm package.

Travis is of course one of if not the most popular CI services out there, and is based on yml configs even for the free tier. We could write an appropriate config file for Bones, which would give people the option of zero-effort Travis usage (regardless of whether Fullstack as an org switches over or not).

_Copied from original issue: queerviolet/bones#17_

**Comment by glebec** [comment]
I researched it out of necessity, since Codeship has been causing some annoying problems as of late. This works:

```yml
language: node_js
node_js:
  - node
services:
  - postgresql
addons:
  postgresql: '9.6'
sudo: false
dist: trusty
```

Suggest making this very easy PR soon.
